const quoteLibrary = [
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Don’t watch the clock; do what it does. Keep going.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The future depends on what you do today.",
    "Believe in yourself and all that you are.",
    "Your time is limited, don't waste it living someone else's life.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Act as if what you do makes a difference. It does.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Never bend your head. Always hold it high. Look the world straight in the eye.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "It is never too late to be what you might have been.",
    "The journey of a thousand miles begins with one step.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Opportunities don't happen, you create them.",
    "Don't let yesterday take up too much of today.",
    "You are never too old to set another goal or to dream a new dream.",
    "To live a creative life, we must lose our fear of being wrong.",
    "Reading is to the mind what exercise is to the body.",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
    "The best way to predict the future is to invent it.",
    "Happiness is not something ready made. It comes from your own actions.",
    "If you want to lift yourself up, lift up someone else.",
    "You miss 100% of the shots you don't take.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "A journey of a thousand miles begins with a single step.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    "The best revenge is massive success.",
    "The only person you are destined to become is the person you decide to be.",
    "Go confidently in the direction of your dreams. Live the life you have imagined.",
    "We generate fears while we sit. We overcome them by action.",
    "The mind is everything. What you think you become.",
    "Start where you are. Use what you have. Do what you can.",
    "Fall seven times and stand up eight.",
    "Everything has beauty, but not everyone can see.",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
    "When I let go of what I am, I become what I might be.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "Happiness is not something you postpone for the future; it is something you design for the present.",
    "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Too many of us are not living our dreams because we are living our fears.",
    "I attribute my success to this: I never gave or took any excuse.",
    "The only way to do great work is to love what you do.",
    "Change your thoughts and you change your world.",
    "It is during our darkest moments that we must focus to see the light.",
    "Believe you can and you're halfway there.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "A person who never made a mistake never tried anything new.",
    "Education is the most powerful weapon which you can use to change the world.",
    "The two most important days in your life are the day you are born and the day you find out why.",
    "People who are crazy enough to think they can change the world, are the ones who do.",
    "Knowing is not enough; we must apply. Willing is not enough; we must do.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "Aim for the moon. If you miss, you may hit a star.",
    "Action is the foundational key to all success.",
    "Don't wait. The time will never be just right.",
    "Success consists of going from failure to failure without loss of enthusiasm.",
    "Be the change that you wish to see in the world.",
    "Strive not to be a success, but rather to be of value.",
    "The power of imagination makes us infinite.",
    "Try to be a rainbow in someone's cloud.",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "Life is really simple, but we insist on making it complicated.",
    "We know what we are, but know not what we may be.",
    "Perfection is not attainable, but if we chase perfection we can catch excellence.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
    "In the middle of every difficulty lies opportunity.",
    "Your time is limited, so don't waste it living someone else's life.",
    "The purpose of our lives is to be happy.",
    "Turn your wounds into wisdom.",
    "Do what you can, with what you have, where you are.",
    "Be yourself; everyone else is already taken.",
    "So many books, so little time.",
    "A room without books is like a body without a soul.",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
    "You accept the love you think you deserve.",
    "Without music, life would be a mistake.",
    "It is our choices, that show what we truly are, far more than our abilities.",
    "If you tell the truth, you don't have to remember anything.",
    "A friend is someone who knows all about you and still loves you.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Always forgive your enemies; nothing annoys them so much.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "We accept the love we think we deserve.",
    "I am so clever that sometimes I don't understand a single word of what I am saying.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Everything you can imagine is real.",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway.",
    "It is better to be hated for what you are than to be loved for what you are not.",
    "Pain is temporary. Quitting lasts forever.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "If you want something you've never had, you must be willing to do something you've never done.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Someone is sitting in the shade today because someone planted a tree a long time ago.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Your time is limited, so don't waste it living someone else's life.",
    "You can't use up creativity. The more you use, the more you have.",
    "I have learned over the years that when one's mind is made up, this diminishes fear.",
    "I would rather die of passion than of boredom.",
    "A truly rich man is one whose children run into his arms when his hands are empty.",
    "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
    "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
    "Build your own dreams, or someone else will hire you to build theirs.",
    "Education costs money. But then so does ignorance.",
    "I have chosen to be happy because it is good for my health.",
    "Remember that the happiest people are not those getting more, but those giving more.",
    "The only true wisdom is in knowing you know nothing.",
    "Be kind, for everyone you meet is fighting a hard battle.",
    "The unexamined life is not worth living.",
    "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
    "Ask not what your country can do for you – ask what you can do for your country.",
    "Genius is one percent inspiration and ninety-nine percent perspiration.",
    "He who has a why to live can bear almost any how.",
    "That which does not kill us makes us stronger.",
    "Life is what happens when you're busy making other plans.",
    "When the going gets tough, the tough get going.",
    "You must be the change you wish to see in the world.",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
    "The only thing we have to fear is fear itself.",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.",
    "Do one thing every day that scares you.",
    "Well done is better than well said.",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    "It is during our darkest moments that we must focus to see the light.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Be yourself; everyone else is already taken.",
    "Action is the antidote to despair.",
    "A smooth sea never made a skilled sailor.",
    "Do what you can, with what you have, where you are.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "It always seems impossible until it’s done.",
    "The power of imagination makes us infinite.",
    "You are enough just as you are.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "Failure is the condiment that gives success its flavor.",
    "Success often comes to those too busy to be looking for it.",
    "Don’t count the days, make the days count.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "The best preparation for tomorrow is doing your best today.",
    "You do not find the happy life. You make it.",
    "Happiness depends upon ourselves.",
    "Believe you can and you’re halfway there.",
    "Act as if what you do makes a difference. It does.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "When you have a dream, you've got to grab it and never let go.",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "No matter what you're going through, there's a light at the end of the tunnel.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "You limit your challenges or challenge your limits.",
    "Don't worry about failures, worry about the chances you miss when you don't even try.",
    "Though the road be rough, it leads to the stars.",
    "Perseverance is not a long race; it is many short races one after the other.",
    "Courage is resistance to fear, mastery of fear—not absence of fear.",
    "Only I can change my life. No one can do it for me.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "The harder the conflict, the more glorious the triumph.",
    "We must accept finite disappointment, but never lose infinite hope.",
    "Try to be a rainbow in someone's cloud.",
    "Nothing is impossible. The word itself says 'I'm possible!'",
    "Keep looking up. That's the secret of life.",
    "You are much stronger than you think.",
    "A champion is defined not by their wins but by how they can recover when they fall.",
    "Motivation comes from working on things we care about.",
    "If you look at what you have in life, you'll always have more.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "Dream big and dare to fail.",
    "The secret of getting ahead is getting started.",
    "Do not let what you cannot do interfere with what you can do.",
    "The obstacle is the way.",
    "He who has a why to live can bear almost any how.",
    "Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.",
    "Happiness is not something readymade. It comes from your own actions.",
    "Whatever you are, be a good one.",
    "Be the change that you wish to see in the world.",
    "In the middle of every difficulty lies opportunity.",
    "Start where you are. Use what you have. Do what you can.",
    "Don’t let yesterday take up too much of today.",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
    "The man on top of the mountain didn't fall there.",
    "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.",
    "People who are crazy enough to think they can change the world, are the ones who do.",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
    "Imagine your life is perfect in every respect; what would it look like?",
    "We generate fears while we sit. We overcome them by action.",
    "Whether you think you can or you think you can’t, you’re right.",
    "Security is mostly a superstition. Life is either a daring adventure or nothing.",
    "Your true success in life begins only when you make the commitment to become excellent at what you do.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Creativity is intelligence having fun.",
    "What you lack in talent can be made up with desire, hustle and giving 110% all the time.",
    "Do what you can with all you have, wherever you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "To live a creative life, we must lose our fear of being wrong.",
    "If you’re not stubborn, you’ll give up on experiments too soon. And if you’re not flexible, you’ll pound your head against the wall and you won’t see a different solution to a problem you’re trying to solve.",
    "Optimism is the one quality more associated with success and happiness than any other.",
    "Always keep your eyes open. Keep watching. Because whatever you see can inspire you.",
    "There is no substitute for hard work.",
    "The difference between a stumbling block and a stepping stone is how you use them.",
    "Success consists of going from failure to failure without loss of enthusiasm.",
    "I attribute my success to this: I never gave or took any excuse.",
    "Focus on being productive instead of busy.",
    "You don’t have to see the whole staircase, just take the first step.",
    "It’s not what you look at that matters, it’s what you see.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "If you can dream it, you can do it.",
    "Do the best you can until you know better. Then when you know better, do better.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "A person who never made a mistake never tried anything new.",
    "I never dreamed about success. I worked for it.",
    "Work hard in silence, let your success be your noise.",
    "Go the extra mile. It’s never crowded there.",
    "Don’t let the noise of others’ opinions drown out your own inner voice.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "The only way to do great work is to love what you do.",
    "Success usually comes to those who are too busy to be looking for it.",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Don't be afraid to give up the good to go for the great.",
    "I failed my way to success.",
    "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
    "If you want to achieve greatness stop asking for permission.",
    "Things work out best for those who make the best of how things work out.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "That which does not kill us makes us stronger.",
    "Life is what happens when you’re busy making other plans.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
    "Many of life’s failures are people who did not realize how close they were to success when they gave up.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Money and success don’t change people; they merely amplify what is already there.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Not how long, but how well you have lived is the main thing.",
    "If life were predictable it would cease to be life, and be without flavor.",
    "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.",
    "In order to write about life first you must live it.",
    "The big lesson in life, baby, is never be scared of anyone or anything.",
    "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth.",
    "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.",
    "Life is not a problem to be solved, but a reality to be experienced.",
    "The unexamined life is not worth living.",
    "Turn your wounds into wisdom.",
    "The way I see it, if you want the rainbow, you gotta put up with the rain.",
    "Don’t settle for what life gives you; make life better and build something.",
    "Everything negative – pressure, challenges – is all an opportunity for me to rise.",
    "I like the criticism. It makes you strong.",
    "You never really learn much from hearing yourself speak.",
    "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this.",
    "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.",
    "Live for each second without hesitation.",
    "Life is like a coin. You can spend it any way you wish, but you only spend it once.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe you can and you're halfway there.",
    "The only impossible journey is the one you never begin.",
    "The best viewing point is the one closest to the ground.",
    "It is during our darkest moments that we must focus to see the light.",
    "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is either a daring adventure or nothing at all.",
    "You must be the change you wish to see in the world.",
    "Spread love everywhere you go.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Opportunities don't happen, you create them.",
    "It is never too late to be what you might have been.",
    "Don't wait. The time will never be just right.",
    "Doubt kills more dreams than failure ever will.",
    "Future belongs to those who believe in the beauty of their dreams.",
    "Dream big and dare to fail.",
    "The road to success and the road to failure are almost exactly the same.",
    "It is better to fail in originality than to succeed in imitation.",
    "Do not let making a living prevent you from making a life.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
    "Nothing in the world can take the place of persistence.",
    "Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable.",
    "I never dreamed about success, I worked for it.",
    "Success is getting what you want, happiness is wanting what you get.",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
    "Don’t let yesterday take up too much of today.",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
    "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.",
    "Experience is a hard teacher because she gives the test first, the lesson afterwards.",
    "To know how much there is to know is the beginning of learning to live.",
    "Goal setting is the secret to a compelling future.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Character is power.",
    "The mind is everything. What you think you become.",
    "The best way to predict your future is to create it.",
    "You are the master of your destiny. You can influence, direct and control your own environment. You can make your life what you want it to be.",
    "Whatever the mind of man can conceive and believe, it can achieve.",
    "Every strike brings me closer to the next home run.",
    "I don’t wait for moods. You accomplish nothing if you do that. Your mind must know it has got to get down to work.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "Either you run the day, or the day runs you.",
    "I’m a greater believer in luck, and I find the harder I work the more I have of it.",
    "When we strive to become better than we are, everything around us becomes better too.",
    "There is no elevator to success. You have to take the stairs.",
    "Be not afraid of going slowly, be afraid only of standing still.",
    "It does not matter how slowly you go as long as you do not stop.",
    "There are no limits to what you can accomplish, except the limits you place on your own thinking.",
    "A year from now you offered wish you had started today.",
    "The only person you are destined to become is the person you decide to be.",
    "We become what we think about.",
    "Life is 10% what happens to me and 90% of how I react to it.",
    "Your time is limited, so don't waste it living someone else's life.",
    "Win from within.",
    "You are your only limit.",
    "Discipline is doing what needs to be done, even if you don't want to.",
    "Work until your idols become your rivals.",
    "Your life does not get better by chance, it gets better by change.",
    "Motivation gets you going, but discipline keeps you growing.",
    "If you want to fly, give up everything that weighs you down.",
    "Don't stop until you're proud.",
    "Focus on the goal, not the obstacle.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Don’t watch the clock; do what it does. Keep going.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The future depends on what you do today.",
    "Believe in yourself and all that you are.",
    "Your time is limited, don't waste it living someone else's life.",
    "Act as if what you do makes a difference. It does.",
    "Efficiency is doing things right; effectiveness is doing the right things.",
    "To handle yourself, use your head; to handle others, use your heart.",
    "Believe you can and you're halfway there.",
    "When something is important enough, you do it even if the odds are against you.",
    "The only way to do great work is to love what you do.",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
    "Life is what happens when you're busy making other plans.",
    "You must expect great things of yourself before you can do them.",
    "I can accept failure, everyone fails at something. But I can't accept not trying.",
    "Some people want it to happen, some wish it would happen, others make it happen.",
    "I've failed over and over and over again in my life. And that is why I succeed.",
    "You miss 100% of the shots you don't take.",
    "Winning isn't everything, but wanting to win is.",
    "It is not the mountain we conquer, but ourselves.",
    "It is better to fail in originality than to succeed in imitation.",
    "The road to success is always under construction.",
    "The only place where success comes before work is in the dictionary.",
    "Don't be afraid to give up the good to go for the great.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
    "There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind.",
    "Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable.",
    "I never dreamed about success. I worked for it.",
    "Success is getting what you want, happiness is wanting what you get.",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
    "Don’t let yesterday take up too much of today.",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
    "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.",
    "Experience is a hard teacher because she gives the test first, the lesson afterwards.",
    "To know how much there is to know is the beginning of learning to live.",
    "Goal setting is the secret to a compelling future.",
    "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.",
    "Either you run the day or the day runs you.",
    "I’m a greater believer in luck, and I find the harder I work the more I have of it.",
    "When we strive to become better than we are, everything around us becomes better too.",
    "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it.",
    "It’s not keeping up with the Joneses. It’s going down to the basics and just being yourself.",
    "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.",
    "All our dreams can come true, if we have the courage to pursue them.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "If you can dream it, you can do it.",
    "Do the best you can until you know better. Then when you know better, do better.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "A person who never made a mistake never tried anything new.",
    "I never dreamed about success. I worked for it.",
    "Work hard in silence, let your success be your noise.",
    "Go the extra mile. It’s never crowded there.",
    "Don’t let the noise of others’ opinions drown out your own inner voice.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "The only way to do great work is to love what you do.",
    "Success usually comes to those who are too busy to be looking for it.",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful."
];


